### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by agrass** [aroth/react-native-uploader#11]
Hi! 

This project is Android compatible or no? Someone is working in an android version??

Best

**Comment by gorangajic** [comment]
@agrass you don't need module like this one to upload files I was also searching for solution and was able to upload files using FormData with `fetch` or `XMLHttpRequest`
https://github.com/facebook/react-native/blob/b9396cd74419dd4165fb051605076d19b1c18905/Libraries/Network/FormData.js#L28

**Comment by agrass** [comment]
Hi @gorangajic, I already use fetch but I liked the interface of this example. You know why is native and not pure javascript?

**Comment by gorangajic** [comment]
I have tried couple of native modules, but at the end decided to use fetch with `FormData` because all packages that I tried had broken(app freezing, slow) or missing android implementation
