### ISSUE TITLE
Upload directly from Camera instead of Camera Roll

### ISSUE THREAD

**Issue by quadsurf** [aroth/react-native-uploader#15]
If I want my users to open camera from within my react native app, record a short video, preview the video, then upload to server/cloud (so app user never sees/interacts with the cameraRoll), is this possible using your plug-in?

**Comment by aroth** [comment]
@quadsurf Not quite. This plugin only handles uploading files already saved to the device or camera roll. It may not be too difficult to develop for your use case if you wanted to fork the project.
