### ISSUE TITLE
Android: NativeModules.FileTransfer does not exist

### ISSUE THREAD

**Issue by GeoffreyPlitt** [aroth/react-native-uploader#16]
Related to #13 

I'm on RN 0.32 and your module gives me "Cannot call upload of undefined" because NativeModules.FileTransfer does not exist.

Your module seems to depend on NativeModules.FileTransfer, but this does not exist for me (I console.log it out and it's NULL)

**Comment by GeoffreyPlitt** [comment]
Any luck?

**Comment by GeoffreyPlitt** [comment]
@aroth @bouchertommy Is this module still maintained?

**Comment by aroth** [comment]
@GeoffreyPlitt  I haven't had the chance to look -- especially not first thing on a Monday. Yes, this module is maintained, but in my spare time and I've been quite busy these days.

I hoped to take a look at this issue within a week or so.  Can you please provide sample code? It'll simplify & speed up matters on my end.

**Comment by GeoffreyPlitt** [comment]
Thanks!

RN 0.32, on Android, any call to RNUploader.upload() will fail with "Cannot call upload of undefined". So it's broken for all Android users, as of RN 0.32, perhaps earlier versions too.

The problem is that NativeModules.FileTransfer is NULL now, and your module seems to depend on it being there.

**Comment by aroth** [comment]
That's the problem -- this module doesn't yet officially support Android.

Two options:
- Apply the changes in this PR: https://github.com/aroth/react-native-uploader/pull/13
- Install from this fork: https://github.com/g6ling/react-native-uploader

I wasn't completely satisfied with the PR and so it wasn't merged. Maybe someday I'll find the time to work on Android support, but as of now, I'm primarily developing for iOS and my schedule leaves very little room. 

Better yet, perhaps somebody from the community will step up to tackle this. I'm very open to PRs.

**Comment by GeoffreyPlitt** [comment]
Ah, thanks!
