### ISSUE TITLE
Cancel upload

### ISSUE THREAD

**Issue by apolkingg8** [aroth/react-native-uploader#2]
As title, is there any way to cancel/abort upload?

**Comment by aroth** [comment]
Yes, this is possible starting with react-native-uploader@0.0.8.

Canceling uploads is simple:

```
RNUploader.cancel();
```

Be sure to update your component's view/state to reflect the cancellation as this method merely cancels the NSURLConnection on the native side.

The example app has also been updated with this feature.

**Comment by apolkingg8** [comment]
Awesome! :beer:
