### ISSUE TITLE
undefined is not an object (evaluating 'RNUploader.upload')

### ISSUE THREAD

**Issue by mdhanju** [aroth/react-native-uploader#20]
Unhandled JS Exception: undefined is not an object (evaluating 'RNUploader.upload')
"react-native": "0.34.1",
x-code 8.1

<img width="845" alt="binary_linking" src="https://cloud.githubusercontent.com/assets/7625083/20608140/99ae789e-b233-11e6-9cff-9eeeeb84ea89.png">

**Comment by aroth** [comment]
Try 0.10. Documentation & the sample app have been updated. Tested against react-native 0.38.  

```
import React, { Component } from 'react';

import {
  StyleSheet,
  Component,
  View,
  DeviceEventEmitter,
} from 'react-native';

var RNUploader = NativeModules.RNUploader;
```

**Comment by abhisekgoldy** [comment]
You need to import NativeModules as well from 'react-native'
