### ISSUE TITLE
Build fails after adding to project (iOS)

### ISSUE THREAD

**Issue by ryanvanbelkum** [aroth/react-native-uploader#30]
Steps to reproduce:

- yarn add react-native-uploader
- react-native link react-native-uploader
- clean project in xcode
- rebuild project in xcode

RCTBridgeModule.h:58:3: Typedef redefinition with different types ('struct (anonymous struct at RCTBridgeModule.h:54:16)' vs 'struct RCTMethodInfo') .  -- I chopped out my file locations from error

react-native 0.50.3
MacOS High Sierra
Xcode Version 9.2 (9C40b)

**Comment by IvanCoronado** [comment]
Same here, have you find any solution @ryanvanbelkum ?

**Comment by ryanvanbelkum** [comment]
@IvanCoronado I ended up forking this repo. Fixed the build issue and made some tweaks to work for me. https://github.com/ryanvanbelkum/react-native-uploader

**Comment by aroth** [comment]
@ryanvanbelkum a PR to fix the build would be nice if you ever have the time.

**Comment by niralivasoya** [comment]
@ryanvanbelkum , Can you please let me know what is the fix you did for the build in iOS. I am trying hard to get the package working but I am getting linking error always. I tried to remove lib from linking library and again added, but no luck.

**Comment by ryanvanbelkum** [comment]
@niralivasoya The import for `RCTBridgeModule.h` has changes. Try this in `ios/RNUloader.m`...
```
-#import "RCTBridgeModule.h"
+#import <React/RCTBridgeModule.h>
```
