### ISSUE TITLE
Help with multipart upload

### ISSUE THREAD

**Issue by rgoldiez** [aroth/react-native-uploader#5]
First let me say that this component is great.  I was able to upload an image (user profile pic) to salesforce.com.  However, I'm struggling to figure out how to compose a multipart POST request.  Salesforce has a number of examples [here](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_input.htm). The particular one I'm interested in is below.

How do I use `react-native-uploader` to send this request?

```
POST /services/data/v35.0/chatter/feed-elements HTTP/1.1
Authorization: OAuth 00DRR0000000N0g!...
User-Agent: Jakarta Commons-HttpClient/3.0.1
Host: instance_name
Content-Length: 845
Content-Type: multipart/form-data; boundary=a7V4kRcFA8E79pivMuV2tukQ85cmNKeoEgJgq
Accept: application/json

--a7V4kRcFA8E79pivMuV2tukQ85cmNKeoEgJgq
Content-Disposition: form-data; name="json"
Content-Type: application/json; charset=UTF-8

{
   "body":{
      "messageSegments":[
         {
            "type":"Text",
            "text":"Please accept this receipt."
         }
      ]
   },
   "capabilities":{
      "content":{
         "description":"Receipt for expenses",
         "title":"receipt.pdf"
      }
   },
   "feedElementType":"FeedItem",
   "subjectId":"005RR000000DmOb"
}

--a7V4kRcFA8E79pivMuV2tukQ85cmNKeoEgJgq
Content-Disposition: form-data; name="feedElementFileUpload"; filename="receipt.pdf"
Content-Type: application/octet-stream; charset=ISO-8859-1

...contents of receipt.pdf...

--a7V4kRcFA8E79pivMuV2tukQ85cmNKeoEgJgq--
```

**Comment by aroth** [comment]
Hi @rgoldiez  -- how far are you getting with this?

**Comment by rgoldiez** [comment]
@aroth - Thanks for the response.  Still stuck.  

Here's what I'm sending 

```
{ url: 'https://bots.my.salesforce.com/services/data/v36.0/connect/communities/0DB6100000000KLGAY/chatter/feed-elements',
  files: 
   [ { name: 'feedElementFileUpload',
       filename: 'image.png',
       filepath: 'file:///Users/rgoldiez/Library/Developer/CoreSimulator/Devices/4D36D070-BD5E-4C17-BF64-28331FD9A5DD/data/Containers/Data/Application/ABCFF4C9-C6E1-42E7-990D-8A3377CA2F30/Documents/images/44077641-6762-4CF3-AB27-37BC5021D4A1.jpg',
       filetype: 'image/png' } ],
  method: 'POST',
  headers: 
   { Accept: 'application/json',
     Authorization: 'Bearer [__removed token__]' },
  params: 
   { 'Content-Type': 'application/json; charset=UTF-8',
     subjectId: 'a0561000001fZIlAAM',
     capabilities: { content: { description: 'Test file upload', title: 'image.jpg' } },
     feedElementType: 'FeedItem' } }
```

I'm getting the follow response back from salesforce.

```
{
  "errorCode":"POST_BODY_PARSE_ERROR",
  "message":"Binary data included but file attachment information is missing. If providing rich JSON/XML input in multipart REST, make sure to include Content-Type header in the part."
}
```

Any help is greatly appreciated!  Note that I'm able to use this component to upload a user profile attachment to salesforce, but that doesn't required a multipart form message... it's just a simple upload to a REST endpoint.

**Comment by rgoldiez** [comment]
@aroth - any ideas?

**Comment by aroth** [comment]
@rgoldiez I've taken on some new work and don't have much time to dig into this specific scenario. It appears that others have had similar issues when posting data to the Salesforce/Chatter API. You can review a few of these here:

https://www.google.com/search?q=%22Binary+data+included+but+file+attachment+information+is+missing%22&oq=%22Binary+data+included+but+file+attachment+information+is+missing%22&aqs=chrome..69i57l2.567j0j7&sourceid=chrome&es_sm=91&ie=UTF-8

It's likely header or param naming issues as other libraries are returning the same response. Or it could be a limitation with this library -- I am not certain. Here is a working code example in Java:

http://salesforce.stackexchange.com/questions/1301/image-upload-to-chatter-post

I think it would be useful to determine what `react-native-uploader` is generating and compare that to input that the Salesforce API is expecting.
